### ISSUE TITLE
Game-specific state machines

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#206]
I've long been intrigued by the way that GreenShell (apparently) compiles game-specific state machines.  I was wondering how much performance we stood to gain, so as a first experiment, I hand-coded a state machine for the C4 family of games.  It isn't based on propnets at all, but still obeys the standard `StateMachine` interface.  It isn't very highly optimized (e.g. it stores the board state in an MxN array of `int`s rather than bit-twiddling), but obviously benefits from being specific to C4.  All in Java (unlike GreenShell, which I think compiles C code).

I tested the single-threaded speed of purely random rollouts from the initial state.  (This meant no memory allocation at all after the initial set-up.)  I compared it with our generic `ForwardDeadReckonPropnetStateMachine` (using the `StateMachinePerformanceAnalyser` in `-statemachine` mode).  Here are the results (in thousands of iterations per second).

Game|Size|Generic|Specific|Factor
---|---|---|---|---
C4|8x6|67|408|6.1
C4 Large|12x9|47|328|7.0
C4 Larger|20x20|34|258|7.6
Majorities|(55)|9|140|15.6

So this represents an upper bound on performance gains and assumes that we're able to do automated analysis and code generation to the same level that I implemented by manual analysis.  I also note that, if I create a new `MachineState` per rollout (which is more realistic, because doing the rollout is destructive), standard C4 performance drops to 348K/s, a factor of 5.2.

Whilst C4 is one of our fastest games (for the generic engine), to be honest, I'm still a little underwhelmed by the results.  I'm likely to leave this on the back burner for now.

**Comment by SteveDraper** [comment]
Agreed - not enough to justify the (massive I expect) work involved.

Two at least somewhat related observations however:

1) Renegeration/re-analysis periodically (to produce a state machine bespoke to the current state as if it were initial) might yield benefits other than better performance of the resulting state machine.  In particular it could easily lead to useful new latch identification

2) Another possibility that occurred to me would be to have a second implementation, still using the same propnet, but animated with a parallel animator (one that uses a 64-bit wide vector and propagates that through the propnet, since logical operator are trivially widened).  The parallel instance would be very efficient in circumstances where you had a batch of 'questions' lined up in the form of vectorized states and inputs.  This would give us a 64-way parallel state machine, so the question then is can you find 64 questions to ask it at once (synchronously) without bottlenecks in getting the 'questions' lined up.  I think you can in two important cases (which are the only ones I would propose using  a parallel state machine instance for):
2.1) Retrieve all next states from the set of legal moves in one fell swoop
2.2) Implement parallel playout to synchronously clock 64 state machines each with their own random path, and thus get a result that is the average of 64 playouts in similar time to getting 1 now

**Comment by arr28** [comment]
Results for Majorities are somewhat better (original post updated) - and interestingly, I think the analysis required for Majorities would be considerably simpler.

**Comment by arr28** [comment]
This idea basically didn't work.  I've split out the parallel state machine idea into #218.  Closing this one.
