### ISSUE TITLE
Not playing from learned plans properly

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#216]
When we get near the end of a learned plan (within `thinkBelowPlanSize` moves), we throw exceptions everywhere and submit nil moves.

**Comment by SteveDraper** [comment]
Fixing it now

**Comment by arr28** [comment]
Fixed by setting `thinkBelowPlanSize = 0`, except when testing.  It's possible that testing from initial plans is also broken, but we can fix that when we come to it.

**Comment by SteveDraper** [comment]
I think that is sticky-tape not really the fix (which I think I have, and am currently testing)

**Comment by arr28** [comment]
Okay then.  Assigning to you for the real fix.  (We should also only use `thinkBelowPlanSize` when testing, so I think my partial fix should stay.)

**Comment by SteveDraper** [comment]
Actually I think **part** of your partial fix should stay.  Specifically it
should default to 0, but if a plan is provided at meta-gaming time (i.e. -
running under PlayerRunner with a pre-specified plan) THEN (and only then)
it should be set to 2.  I will change it to work that way.

**Comment by SteveDraper** [comment]
I'm still getting this even with both our fixes (or something similar anyway) about 1 game run in 30!  Leaving this open to complete when I return from my trip as I have to go catch a plane now!

**Comment by SteveDraper** [comment]
Ok found the residual issue - it's quite an obscure case where a forced move sequence from (new) root state to a terminal node has to be expanded to reconnect the new root to the existing tree, and the existing terminal node already has an alternative path by which it is reachable from the old root (previous turn's root).  Since this expansion occurs during the setting up of the new root, the now-unreachable parts of the tree have not yet been trimmed and it can attempt to cache a plan that takes the 'wrong' path from the old root and hence does not lead back to the current root.  The code did not handle this case.  Fix currently soak testing...
