### ISSUE TITLE
Double move distance analysis

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#221]
This looks a little unlikely.  (There's only 1 Sancho instance running.)  From the start of a Tiltyard game...

```
21:57:26.181 - Begin analysing move distances...
21:57:26.184 - Begin analysing move distances...
21:57:26.234 - Base props are coupled through the terminality logic
21:57:26.234 - Completed analysing move distances...
21:57:26.234 - Local search not supported for this game
21:57:26.240 - Base props are coupled through the terminality logic
21:57:26.240 - Completed analysing move distances...
```

**Comment by arr28** [comment]
Or perhaps we're doing it once for each player?

**Comment by SteveDraper** [comment]
Shouldn't be.  Just seems like a bug.  I'd worry slightly that we might be
creating two local searcher instances!  I obviously need to look into it

**Comment by arr28** [comment]
I don't think there's more than 1 copy running.

The first stack is when the Move Consequence Processor starts running.

```
Daemon Thread [Move Consequence Processor] (Suspended (breakpoint at line 977 in LocalRegionSearcher))	
	LocalRegionSearcher.generateMoveDistanceInformation() line: 977	
	LocalRegionSearcher.canPerformLocalSearch() line: 146	
	MoveConsequenceSearcher.run() line: 130	
	Thread.run() line: not available	
```

The second stack is when we start searching for a move.  Before telling the MoveConsequenceSearcher what our new root is, we check to see if it is enabled.

```
Thread [GamePlayer - Sancho 1.60t (9147)] (Suspended (breakpoint at line 977 in LocalRegionSearcher))	
	LocalRegionSearcher.generateMoveDistanceInformation() line: 977	
	LocalRegionSearcher.canPerformLocalSearch() line: 146	
	MoveConsequenceSearcher.isEnabled() line: 46	
	GameSearcher.startSearch(long, ForwardDeadReckonInternalMachineState, short, ForwardDeadReckonLegalMoveInfo) line: 849	
	Sancho.stateMachineMetaGame(long) line: 999	
	Sancho(StateMachineGamer).metaGame(long) line: 208	
	StartRequest.process(long) line: 71	
	GamePlayer.run() line: 110	
```

Various possible approaches to this.

- Not clear to me that a method called `isEnabled` (in this case `MoveConsequenceSearcher.isEnabled`) should be calling `canPerformLocalSearch`.  I'd have expected an `isEnabled` method to just read off some aspect of the object's state.
- Not clear that the `GameSearcher` needs to worry whether the `MoveConsequenceSearcher` is enabled.  No harm in the `GameSearcher` telling the `MoveConsequenceSearcher` what the new root is anyway - even if the `MoveConsequenceSearcher` isn't going to use the information.

**Comment by SteveDraper** [comment]
It's a race condition.  isEnabled() essentially does just read off the state, BUT on first call it demand calculates that piece of state.  Because we call it from inside the MoveConsequenceSearcher's thread to determine whether to actually bother doing anything, AND from the main search thread to determine whether there is any need to provide it with moves to search, the lack of locking results in a race condition, where both threads can kick off the construction of the distance table.

Trivially fixed by moving the check at the start of the MoveConsequenceSearcher out of that thread and instead making to call to determine whether to even spawn the thread at all.  That puts the first call to it unambiguously on the game searcher thread with no race.

I wanted to make the checks so as to minimize overhead where it's not being used, though admittedly it's low.
