### ISSUE TITLE
Centipede is classified as fixed length

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#230]
Whilst trying to determine game length during meta-gaming, we think that Centipede has fixed length 17.  That isn't even remotely true.  At each turn, each player can choose to end the game.

There must be something dodgy with the simulations.

**Comment by arr28** [comment]
Greedy rollouts are on.  There appears to be a bug in `transitionToNextStateInGreedyRollout`.  At line 3537, we decide there's only 1 remaining move to consider (because `preEnumerate` is false - in which case we always assume there's just 1 move to consider).

As a result, this routine only ever considers the first move (`continue`) and never the other option (`finish`).  Because of this, all games appear to be of maximum length (17).

I'm deep enough into this that I don't really know what's happening any more.  Were we wrong to be using greedy rollouts during this part of meta-gaming?  Were the greedy rollouts wrong to be just examining 1 out of 2 moves?

Please could you take a look, Steve?

**Comment by SteveDraper** [comment]
Will do

**Comment by SteveDraper** [comment]
Not really a bug per se (at least not a serious one).  The issue is that greedy rollouts are doing their job!  Specifically, if a move leads immediately to termnination, but the goal for the chooser was not the optimal goal value achievable (from that state) then greedy rollouts choose another move.  In Centipede this forces only 'continue'; to ever be played.

This effect however, does make it inappropriate to be running with greedy rollouts on to determine the range of possible game lengths.  Since we MUST have them on in the simulation loop where game lengths are currently measured (because we have to assess their effectiveness) this is a bit awkward.  I have modified things to also measure a rough game length range in the shorter initial simulation loop, and:
1) Used that to assert it cannot be an iterated game
2) Turned greedy rollouts off for that loop
This necessitated some enhancement of the state machine to allow greedy rollouts to be temporarily turned off, and then back on again, which was not previously supported
