### ISSUE TITLE
Failing to reliably solve Multiple Hamilton

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#234]
Multiple Hamilton has a left and a right board for trying to perform a Hamiltonian-circuit on.  However, only the right board makes any difference to the score.

We reliably solve regular Hamilton, but often fail to solve Multilple Hamilton, if time or computing resources are limited.  On my quad-core, Hamilton is solved in a smidge over a second...

```
13:57:43.710 - Move search started
13:57:44.971 - Mark root complete
```

...whilst Multiple Hamilton takes the best part of a minute.

```
14:00:45.017 - Move search started
14:01:40.462 - Mark root complete
```

Presumably we're failing to discard the irrelevant choices / factor the game.

**Comment by SteveDraper** [comment]
From memory, I think we don't factorize puzzles, though we should discard
'irrelevant' propositions, which will (should) include any isolated
sub-games whose state does not contribute to the goals.

**Comment by SteveDraper** [comment]
removeIrrelevantBasesAndInputs() in the optimizing factory is supposed to
do this.  Looking at the rules to multiple Hamilton I think it should be
eliminating one 'board' here.  It does do so in multiple TicTacToe (I
think!), so there must be some subtle difference...

**Comment by SteveDraper** [comment]
Well, this WAS a can of worms!  Turns out that the coupling between boards in dual Hamilton is much less obviously redundant than other cases due to these rules:

  (<= (next (location ?s ?y))
      (does robot (move ?r ?x))
      (true (location ?s ?y))
      (distinct ?r ?s))

  (<= (next (score ?s ?n))
      (does robot (move ?r ?y))
      (true (score ?s ?n))
      (distinct ?r ?s))

The distinct clauses couple preservation of base props on one board to moves on the other (because the GDL uses move on board A effectively as a proxy for not moving on board B).

I managed to detect this case by checking for (simple) latched base props being settable by some OTHER path than a cross-coupling one, since a possible-not-required base prop that is a latch can only become set by some other path, so if the OTHER paths are also fed from apparent-not-required does/base props it can never become set and so force things that are dependent on it to be required.  This is actually moderately subtle and complicated to do, so took a while to debug with respect to regression testing other games!  In the course of testing I also discovered some minor bugs and inefficiencies in the redundant gate removal code, which I have also fixed.

Regressions tested against all the factorizable Stanford puzzles and a few factorizable 2-player games, plus all the state machine validator (full rtun against all games it doesn't explicitly inhibit testing of)

**Comment by arr28** [comment]
Sorry it was a tricky one.  Certainly seems to have sorted the problem though...

```
19:38:16.560 - Move search started
19:38:24.662 - Mark root complete
```

Down to 8 seconds to solve Multiple Hamilton.  Still oddly longer than regular Hamilton, but at 8 seconds, there's no point in further examination.

I've removed the test work-around (which apparently wasn't quite enough anyway!).

**Comment by SteveDraper** [comment]
I have seen it score 95 still even with (verified) correct reduction to the
single board.  However, it's much much rarer now
