### ISSUE TITLE
Unlikely claim of no goals in stanford.yinsh

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#322]
When playing stanford.yinsh, we claim...

```
17:36:12.584 ! Invalid GDL.  No goals defined for our role (black)!  We will crash.
```

But the GDL includes the following, so I'm surprised.

```
    (<= (goal black 100)
        (not (line white))
        (line black))
      
    (<= (goal black 50)
        (not (line white))
        (not (line black)))
  
    (<= (goal black 0)
        (line white)
        (not (line black)))
```

**Comment by SteveDraper** [comment]
This is broken GDL I believe.  At any rate, it's certainly GDL the basic propnet generator cannot cope with (before we get to any of our optimization routines).  I **think** the issue is with the 'line' rules (which do not appear in the propnet the base generator starts with, and thus everything that derives from them is also absent, which includes all goals, and all but 1 termination condition).  The problem appears to be this (example of one line rule plus the ordering definition):

(<= (line ?r)
            (role ?r)
            (true (cell   ?x1  ?y1  ?r))
            (true (cell   ?x2  ?y2  ?r))
            (true (cell   ?x3  ?y3  ?r))
    (true (cell   ?x4  ?y4  ?r))
    (true (cell   ?x5  ?y5  ?r))
    (true (order ( ?x1  ?x2  ?x3  ?x4  ?x5)))
    (true (order (?y1 ?y2 ?y3 ?y4 ?y5))))

(order (1 2 3 4 5))
(order (2 3 4 5 6))
(order (3 4 5 6 7))
(order (4 5 6 7 8))
(order (5 6 7 8 9))
(order (6 7 8 9 10))
(order (7 8 9 10 11))

'order' is not a base prop.  It's a rule.  Hence the use of expressions like '(true (order ( ?x1  ?x2  ?x3  ?x4  ?x5)))' is incorrect (should just be '(order ( ?x1  ?x2  ?x3  ?x4  ?x5))').

**Comment by arr28** [comment]
Agree.  Not the first time I've seen base prop / rule mix-ups in the Stanford repo.
