### ISSUE TITLE
Use A* for Rubik's Cube

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#375]
Did we attempt to use A* for solving the Rubik's Cube puzzle in the Tiltyard?  (Logs in `data/competitionlogs/TiltyardOpen20151204`.)

If not, why not?

Is so, presumably we didn't find a complete solution in meta-gaming time.  But what was the best result we found?  Could we have used that in preference to anything we saw with MCTS?

**Comment by SteveDraper** [comment]
I took a look at this and the answer is no we didn't, and no we couldn't have anyway.

We didn't because the target state it found didn't meet the criterion set for plausibility (which is that it has at least half as many props set as does the initial state).

We couldn't have because we have no useful distance metric between the current and target states.  This is because the base pops are of the form of a hierarchy of tiles, solidly colored lines, and finally solidly colored faces, with the target state just being the correctly oriented solid faces.  Since hoise props are very sparse in a random set of states (or indeed in a real solution path) they do not form a useful basis for a distance measure.
