### ISSUE TITLE
Relevant components removed by removeIrrelevantBasesAndInputs

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#45]
For base.firefighter, `OptimizingPolymorphicPropNetFactory#removeIrrelevantBasesAndInputs` removes `legal firefighter extinguish` and `does firefighter extinguish`.  However, this move is far from irrelevant.  It's only by doing this move (repeatedly) that you can score 100.

The routine is commented....

```
    //  Any bases and inputs that cannot be reached by tracing back from either the terminal
    //  or a goal proposition are irrelevant (transiting through a virtual does->legal back-link)
```

...which makes an invalid assumption.  In firefighter, "extinguish" does basically nothing.  Therefore, it "cannot be reached by tracing back from either the terminal or a goal proposition".  All the other moves do something - something bad.

The game is won when the step counter reaches 50 (I think) and you haven't made any of the decoy moves.

**Comment by SteveDraper** [comment]
The problem was in the greedy rollout routine that used the winning move proposition as a return value, with null signifying no found winning move.  In this case the winning move has a null prop, and things got VERY confused, with it repeatedly trying the same move, and never recursing on beyond the move penultimate to the win.  Easy fix by replacing the prop with the actual move.
